services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.env.dev.db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgresql://$$POSTGRES_USER:$$POSTGRES_PASSWORD@localhost/$$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
