name: Bug report (cosmetic only)
description: Report cosmetic bugs that do not otherwise affect gameplay or logic progression.
title: "[Bug - Cosmetic]: "
labels: [bug]

body:
  # ─────────────────────────────────────────────
  # Intro / warning text
  # ─────────────────────────────────────────────
  - type: markdown
    attributes:
      value: |
        **PLEASE DO NOT USE THIS FORM TO REQUEST FEATURES!  
        This form is for bug reports only**.

  # ─────────────────────────────────────────────
  # Required confirmation
  # ─────────────────────────────────────────────
  - type: checkboxes
    id: confirmations
    attributes:
      label: Do this first
      options:
        - label: I have read the [support guidelines](https://github.com/Super-Mario-RPG-Randomizer/smrpg_web_randomizer/blob/beta/SUPPORT.md) to make sure my issue is legitimate and not already known.
          required: true

  # ─────────────────────────────────────────────
  # Platform info
  # ─────────────────────────────────────────────
  - type: input
    id: platform
    attributes:
      label: Console or Emulator
      description: |
        If emulator, state which emulator and version.  
        If console, state which flash cart firmware.
      placeholder: "e.g. bsnes 115, FXPak Pro 1.11.2"
    validations:
      required: true

  # ─────────────────────────────────────────────
  # Flags
  # ─────────────────────────────────────────────
  - type: textarea
    id: flags
    attributes:
      label: Flags
      description: Paste the flag string, if available. We need this because your cosmetic settings are not included in the seed permalink.
    validations:
      required: false

  # ─────────────────────────────────────────────
  # Seed / permalink
  # ─────────────────────────────────────────────
  - type: textarea
    id: seed
    attributes:
      label: Seed number / hash or permalink
      description: |
        Provide ONE of the following:  
        • Seed number or hash (from filename or download page)  
        • Permalink URL (from download page)
      placeholder: |
        Seed: 123456
        OR
        https://randomizer.smrpgspeedruns.com/h/123456abcdef
    validations:
      required: true

  # ─────────────────────────────────────────────
  # Seed / permalink
  # ─────────────────────────────────────────────
  - type: textarea
    id: ow
    attributes:
      label: Who is your OVERWORLD character?
      description: |
        This depends on your cosmetics settings which are not baked into the hash.
    validations:
      required: true

  # ─────────────────────────────────────────────
  # Bug description
  # ─────────────────────────────────────────────
  - type: textarea
    id: description
    attributes:
      label: Description of problem
      description: What happened? What did you expect to happen?
    validations:
      required: true