name: Feature request
description: Suggest an idea for a new feature you would like to see added to the randomizer.
title: "[Feature]: "
labels: [enhancement]

body:
  - type: textarea
    id: idea
    attributes:
      label: Suggestion
      description: What is your suggestion? Provide as much detail as you can.
    validations:
      required: true

  - type: checkboxes
    id: confirmations
    attributes:
      label: Support guidelines
      options:
        - label: I have read the [guidelines and design philosophy](https://github.com/Super-Mario-RPG-Randomizer/smrpg_web_randomizer/tree/beta?tab=contributing-ov-file#design-philosophy) that feature suggestions are supposed to follow.
          required: true
        - label: I acknowledge that SMRPG Randomizer is 100% a volunteer project. If my suggestion does not get implemented, I will either (1) accept that outcome or (2) implement it myself.
          required: true
