# Generated by Django 6.1.1 on 2026-09-08 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=1000, unique=True)),
                ('seed', models.BigIntegerField()),
                ('version', models.CharField(max_length=16)),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('debug_mode', models.BooleanField(default=False)),
                ('flags', models.TextField(default='')),
                ('file_select_char', models.CharField(default='', max_length=100)),
                ('file_select_hash', models.CharField(default='', max_length=100)),
                ('race_mode', models.BooleanField(default=False)),
                ('spoiler', models.JSONField(default=dict)),
                ('placement', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=1000)),
                ('patch', models.BinaryField(blank=True, null=True)),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomizer.seed')),
            ],
        ),
        migrations.CreateModel(
            name='SpriteRender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_as_starter', models.BooleanField()),
                ('blob', models.BinaryField()),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprite_renders', to='randomizer.seed')),
            ],
            options={
                'unique_together': {('seed', 'play_as_starter')},
            },
        ),
    ]
