# Generated by Django 6.1 on 2026-08-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0008_race_mode_spoiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='placement',
            field=models.TextField(blank=True, default=''),
        ),
    ]
