# Generated by Django 6.1 on 2026-09-02 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0009_seed_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpriteRender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_as_starter', models.BooleanField()),
                ('blob', models.TextField()),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprite_renders', to='randomizer.seed')),
            ],
            options={
                'unique_together': {('seed', 'play_as_starter')},
            },
        ),
    ]
